name: Setup
description: Checkout, install, and build
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - run: yarn install --immutable
      shell: bash
