name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build browser extension packages
        run: yarn dist:all

      - name: Upload builds to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
